### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by Tigraine** [milgner/TeamCityRedmine#2]
Hi,

great project. Would love to use this in for my Teamcity server but I may simply be too stupid to build it.
I'm now running maven, but I don't have the TeamCity stuff installed on the machine that's defined in the tasks.

Is there any chance you can upload a compiled package of the plugin?

greetings Daniel

**Comment by milgner** [comment]
Hi Daniel,

no problem, I can upload a compiled version of the plugin. It requires the TeamCity distribution to build as the interfaces and 3rd party libraries are defined there and I didn't want to copy them into the project, not least because I'm not sure about possible licensing issues with TeamCity.
I'll message you as soon as I update the project, which will hopefully be this evening.

All the best
Marcus

**Comment by milgner** [comment]
Closing this issue, I'll continue to supply builds through the "Downloads"-feature of Github
